// Generates original puzzles from seeded random positions. Run: npx tsx scripts/genPuzzles.ts
// Output (src/puzzleData.ts) is committed; src/puzzles.test.ts re-verifies every puzzle.
import { Chess } from 'chess.js';
import { writeFileSync } from 'node:fs';
import { matesNow, forcesMate2 } from '../src/puzzles';
import { findWin, type Stone } from '../src/games/gomoku';

let seed = 20261006;
const rnd = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 2 ** 32; };
const pick = <T,>(a: T[]) => a[Math.floor(rnd() * a.length)];

const chess: { id: string; kind: string; fen: string }[] = [];
const seen = new Set<string>();
const t0 = Date.now();
while ((chess.filter((p) => p.kind === 'mate1').length < 14 || chess.filter((p) => p.kind === 'mate2').length < 8) && Date.now() - t0 < 240_000) {
  const g = new Chess();
  const plies = 14 + Math.floor(rnd() * 40);
  for (let i = 0; i < plies && !g.isGameOver(); i++) {
    // mildly greedy playouts reach tactical positions
    const ms = g.moves({ verbose: true }); const caps = ms.filter((m) => m.captured || m.san.includes('+'));
    g.move(rnd() < 0.5 && caps.length ? pick(caps) : pick(ms));
  }
  if (g.isGameOver() || g.isCheck()) continue;
  const fen = g.fen(); if (seen.has(fen)) continue; seen.add(fen);
  const m1 = matesNow(g);
  if (m1.length === 1 && chess.filter((p) => p.kind === 'mate1').length < 14) { chess.push({ id: '', kind: 'mate1', fen }); continue; }
  if (m1.length === 0 && chess.filter((p) => p.kind === 'mate2').length < 8) {
    const firsts = g.moves({ verbose: true }).filter((m) => forcesMate2(g, m));
    if (firsts.length === 1) chess.push({ id: '', kind: 'mate2', fen });
  }
}
chess.forEach((p, i) => { p.id = 'c' + (i + 1); });

// gomoku: templates with distractor stones, verified by brute force
const N = 15; const gomoku: any[] = []; const wins = (b: (Stone | null)[], i: number, w: Stone) => { const c = b.slice(); c[i] = w; return findWin({ size: N, board: c }, i).length > 0; };
const DIRS = [[1, 0], [0, 1], [1, 1], [1, -1]];
for (let tries = 0; gomoku.length < 16 && tries < 20000; tries++) {
  const kind = gomoku.length % 2 === 0 ? 'win1' : 'block1';
  const [dx, dy] = pick(DIRS); const x0 = 2 + Math.floor(rnd() * 8), y0 = 2 + Math.floor(rnd() * 8);
  const line = [0, 1, 2, 3, 4].map((k) => [x0 + dx * k, y0 + dy * k]);
  if (line.some(([x, y]) => x < 0 || y < 0 || x >= N || y >= N)) continue;
  const gap = Math.floor(rnd() * 5); const cells = line.map(([x, y]) => y * N + x);
  const mine = cells.filter((_, k) => k !== gap); // four of five with one hole
  const board: (Stone | null)[] = Array(N * N).fill(null);
  const owner: Stone = kind === 'win1' ? 'B' : 'W';
  mine.forEach((i) => { board[i] = owner; });
  // balance: black count == white count so Black is to move
  const need = (c: Stone) => board.filter((v) => v === c).length;
  let guard = 0;
  while ((need('B') !== need('W') || guard < 6) && guard < 60) { guard++; const i = Math.floor(rnd() * N * N); if (board[i] || cells.includes(i)) continue; board[i] = need('B') > need('W') ? 'W' : 'B'; }
  if (need('B') !== need('W')) continue;
  const mover: Stone = 'B';
  const winners = board.map((v, i) => (v === null && wins(board, i, mover) ? i : -1)).filter((i) => i >= 0);
  const foeWins = board.map((v, i) => (v === null && wins(board, i, 'W') ? i : -1)).filter((i) => i >= 0);
  if (board.some((v, i) => v && findWin({ size: N, board }, i).length)) continue;
  if (kind === 'win1' && winners.length === 1 && foeWins.length === 0) { /* ok */ }
  else if (kind === 'block1' && winners.length === 0 && foeWins.length === 1) { /* ok */ }
  else continue;
  gomoku.push({ id: 'g' + (gomoku.length + 1), kind, size: N, black: board.flatMap((v, i) => (v === 'B' ? [i] : [])), white: board.flatMap((v, i) => (v === 'W' ? [i] : [])), toMove: mover });
}
writeFileSync('src/puzzleData.ts', `// GENERATED by scripts/genPuzzles.ts (seeded). Do not edit by hand.\nexport const CHESS_PUZZLES = ${JSON.stringify(chess)};\nexport const GOMOKU_PUZZLES = ${JSON.stringify(gomoku)};\n`);
console.log('chess', chess.length, 'gomoku', gomoku.length, 'ms', Date.now() - t0);
